geo location action docs
Pepperi-Addons/client-actions-docs pull request #2
Opened 2022-02-02 08:45 UTC by simcha-waintrob

2022-02-17 11:58 UTC, Chasky-H requested changes

2022-02-17 11:58 UTC, Chasky-H commented on actions/geo-location.md
> +* HIGH (Accuracy of meters)
See if this definition will hold up for android and web as well

2022-02-17 11:58 UTC, Chasky-H commented on actions/geo-location.md
> +#### WaitTime
MaxWaitTime
or
MaxCaptureTime

2022-02-17 11:58 UTC, Chasky-H commented on actions/geo-location.md
> +If a location is not received within the indicated time, the action will fail.
The action can return whatever accuracy we did manage to capture in that time.
Is there any way we can return the accuracy to the user (not sure this is available on all platforms)

2022-02-17 11:58 UTC, Chasky-H commented on actions/geo-location.md
> +const res = await pepperi.client.captureGeoLocation('HIGH', 3000);
parameters should always be an object so that we can add stuff later without breaking the API

2022-02-17 14:56 UTC, simcha-waintrob commented on actions/geo-location.md
> +* HIGH (Accuracy of meters)
The web has regular and high.
Android has also 3 levels.

2022-02-21 09:50 UTC, Chasky-H commented on actions/geo-location.md
> +Capture current user's geo location.
user's current geo location

2022-02-21 09:50 UTC, Chasky-H commented on actions/geo-location.md
> +if (res.Success) {
res.success

2022-02-21 09:50 UTC, Chasky-H commented on actions/geo-location.md
> +if (res.Success) {
all client API is cpi-node should be camelCase
all Client Action API should be PascalCase

2022-02-21 13:52 UTC, Chasky-H approved these changes

2022-02-21 13:53 UTC, Chasky-H commented
@simcha-waintrob please merge master into your branch

2022-02-22 15:41 UTC, simcha-waintrob commented
> @simcha-waintrob please merge master into your branch

done

2022-02-23 10:32 UTC, Chasky-H approved these changes

2022-02-23 10:32 UTC, merged