hud action documentatino
Pepperi-Addons/client-actions-docs pull request #4
Opened 2022-02-02 16:34 UTC by simcha-waintrob

2022-02-08 09:21 UTC, lihi-sheffer commented on actions/hud.md
> +The key of the HUD.
the hud key which is generated by the client

2022-02-08 09:25 UTC, lihi-sheffer commented on actions/hud.md
> +The client's HUD key that the action will refer to (mandatory in both states 'show' and 'polling').
the client should generate this key as response to show request. further requests will use this key

2022-02-08 09:36 UTC, lihi-sheffer commented on actions/hud.md
> +    "HUDKey": "8A6D7F6D-08AD-4386-85CF-35F726F73339"
the HudKey should be returned only from the show request.

2022-02-08 09:50 UTC, lihi-sheffer commented on actions/hud.md
> +await pepperi.client.showHUD(hudOptions);
consider return value - whether the block completed or canceled

2022-02-08 15:24 UTC, simcha-waintrob commented on actions/hud.md
> +await pepperi.client.showHUD(hudOptions);
like this?
`{ 
        "cancled": true
}`

2022-02-08 15:26 UTC, simcha-waintrob commented on actions/hud.md
> +await pepperi.client.showHUD(hudOptions);
@Chasky-H  what do you think?

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> + It's helpful to give the user an indication that something happens now,
something is happening

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +performing web requests or computing any computations that take a long time. \
takes

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +the action have 3 states.
The action has

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +The state of the HUD action (mandatory).
The values of state can be:

(enum should be PascalCase)

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +In addition, the HUD can show a button that allow the user to close the HUD. the button will be shown only if ```CancelMessage``` text is provided.
What does the client do when the user presses the CancelMessage

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +Tell the client to poll after the interval time in seconds  (mandatory in 'show' state).
The client should poll the emit-event loop after interval time (in seconds).
The client should do so using the CallbackKey of this action.

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +Indicate if the action is succedded.
if the action succeeded

2022-02-09 18:42 UTC, Chasky-H commented on actions/hud.md
> +#### state: show
states should be PascalCase

2022-02-10 12:11 UTC, Chasky-H requested changes

2022-02-10 12:11 UTC, Chasky-H commented on actions/hud.md
> +* Polling
Poll

2022-02-14 07:26 UTC, Chasky-H approved these changes

2022-02-14 07:26 UTC, merged